#!/bin/bash -xv

WORK=/usr/local/bin/cl-ap-inter.work

[[ ! -t 0 ]] && EXEC="xterm -e" || EXEC="source"
# Prevent spanning another xterm if we in
[[ ${TERM} = "xterm" ]] && EXEC="source"

${EXEC} ${WORK}
